<a href="https://colab.research.google.com/github/leo1929/Dataset_Coffee/blob/main/Creacion_Base_de_datos_Ficticia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Esto es un ejercio para la creación de una base de datos ficticia de una tienda la cual vende 4 tipos de productos.



1.   Electrodomesticos
1.   Ropa
2.   Bicicletas
2.   Comida

Creado y desarrolado por: [BOSS LEO PAPI](https://www.linkedin.com/in/leo-hernandez-datasciencee/)

In [1]:
#Importación de librerias a usar
import pandas as pd
import random
!pip install faker
from faker import Faker

Collecting faker
  Downloading Faker-18.13.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 34.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-18.13.0

# Descripción de las tablas a usar:

## 1. La tabla clientes tendra estos campos:

* ID, usar numeros con una longitu de 10 cifras.
* Nombre, Nombres aleatorios en Español
* Edad, edades desde 15 hasta maximo 100
* Correo electronico, tomo las 4 primeras letras del hombre y 2 numeros aleatorios
* Telefono, números con el indicativo +57 para saber que son Colombianos y su respectivo operador.

## 2. La tabla Productos tendra estos campos:
* ID
* Categoria, estas son las categorias:
  1. Ciclismo:
  MTB, Ruta, Gravel

  2. Electrodomesticos:
  Pc, Tablet, Celular

  3. Ropa:
  Formal, Casual, Exclusiva
  
  4. Comida:
  Vegana, Italiana, Francesa

* Precio, estaran en dolares, aleatoriamente desde 10 USD hasta 8900 USD, por categorias:

  1. Ciclismo:
  700 USD a 8900 USD aleatoriamente

  1. Electrodomesticos:
  100 USD a 2000 USD aleatoriamente

  1. Ropa:
  10 USD a 6900 USD aleatoriamente

  1. Comida:
  10 USD a 1200 USD aleatoriamente

## 3. La tabla Ventas tendra estos campos:

* ID Venta
* Fecha, en orden Año/Mes/Día
* ID Cliente, tiene que ir realacionado con el ID de la tabla clientes
* ID Producto, tiene que ir realacionado con el ID de la tabla productos
* Cantidad, Valores de venta de cada uno de los productos
* Total, Valor total en ventas USD

## 4. La tabla Opiniones tendra estos campos:

* ID opinión
* ID Cliente, tiene que ir relacionado con el ID de la tabla clientes
* ID Producto, tiene que ir relacionado con el ID de la tabla de producto
* Opinión:
  1. None
  1. Mala
  1. Rgular
  1. Aceptable
  1. Buena
  1. Excelente

Con esta base de datos se busca hacer ejercicios de análisiss de datos, manejor de estos, graficas, reportes en programas como Power BI, Tableu entre otros y practicar SQL.

In [8]:
# Crear instancia en Faker para la creación de nombres en español aleatoriamente
faker = Faker('es_ES')

# Lista de opciones de números de teléfono con los principales operadores [Tigo, Claro, Movistar, Wom]
opciones_telefono = ['300', '301', '302', '303', '304', '324', '310', '311', '312', '313', '314', '320', '321', '322', '323', '315', '316', '317', '318', '319']

# Crear lista de nombres de clientes
nombres_clientes = [faker.first_name() for _ in range(100)]                     #Lista de 100 Clientes aleatorios en español

# Crear tabla Clientes
clientes_data = {
    'ID': [str(random.randint(1000000000, 9999999999)) for _ in range(100)],    #Numeros de "Cedula aleatorios de 10 cifras"
    'Nombre': nombres_clientes,
    'Edad': [random.randint(15, 100) for _ in range(100)],                      #Lista de 100 edades aleatorias de 15 hasta 100 años
    'Correo electrónico': ['{}{}@gmail.com'.format(nombre[:4].lower(), random.randint(10, 99)) for nombre in [n[:4] for n in nombres_clientes]],
     #Lista de 100 elementos, uso las primeras 4 letras de la columna Nombre seguido de 2 numeros aleatorios
    'Teléfono': ['+57 {} {}'.format(random.choice(opciones_telefono), random.randint(1000000, 9999999)) for _ in range(100)],
     #Lista de 100 datos, Genero número aleatorios con el formato [+57 {opción_telefono} {número_telefono}]
}
clientes_df = pd.DataFrame(clientes_data)
display(clientes_df)

            ID            Nombre  Edad Correo electrónico         Teléfono
0   5708203220              León    63   león97@gmail.com  +57 323 3958243
1   5464378530          Leocadio    43   leoc51@gmail.com  +57 320 7309669
2   5894560910          Evaristo    85   evar61@gmail.com  +57 322 9016023
3   7937817390             Perla    74   perl80@gmail.com  +57 317 4068788
4   3052796549            Amador    26   amad17@gmail.com  +57 319 4933586
..         ...               ...   ...                ...              ...
95  2543459901            Silvia    19   silv23@gmail.com  +57 315 4467853
96  1827497612  Francisco Javier    51   fran50@gmail.com  +57 314 5717984
97  7047127168            Samuel    83   samu89@gmail.com  +57 312 7076611
98  1052355702          Humberto    21   humb53@gmail.com  +57 301 6800637
99  5429200787          Benjamín    62   benj25@gmail.com  +57 315 8271958

[100 rows x 5 columns]

In [9]:
# Crear tabla Productos
categorias = ['Ciclismo', 'Electrodomesticos', 'Ropa', 'Comida']
subcategorias = {
    'Ciclismo': ['MTB', 'Ruta', 'Gravel'],
    'Electrodomesticos': ['Pc', 'Tablet', 'Celular'],
    'Ropa': ['Formal', 'Casual', 'Exclusiva'],
    'Comida': ['Vegana', 'Italiana', 'Francesa']
}

productos_data = {
    'ID Producto': range(1, 101),
    'Categoria': [],
    'Precio USD': [],
}

for _ in range(100):
    categoria = random.choice(categorias)
    subcategoria = random.choice(subcategorias[categoria])
    productos_data['Categoria'].append(f'{categoria} - {subcategoria}')

    if categoria == 'Ciclismo':
        productos_data['Precio USD'].append(random.randint(700, 8900))
    elif categoria == 'Electrodomesticos':
        productos_data['Precio USD'].append(random.randint(100, 2000))
    elif categoria == 'Ropa':
        productos_data['Precio USD'].append(random.randint(10, 6900))
    elif categoria == 'Comida':
        productos_data['Precio USD'].append(random.randint(10, 1200))

productos_df = pd.DataFrame(productos_data)
display(productos_df)

    ID Producto                   Categoria  Precio USD
0             1           Comida - Italiana         928
1             2               Ropa - Casual        3872
2             3           Ciclismo - Gravel        7974
3             4               Ropa - Casual        5143
4             5               Ropa - Casual        5418
..          ...                         ...         ...
95           96              Ciclismo - MTB        5226
96           97  Electrodomesticos - Tablet         746
97           98             Ciclismo - Ruta        3613
98           99           Comida - Francesa         291
99          100               Ropa - Casual        1285

[100 rows x 3 columns]

In [10]:
# Crear tabla Ventas
ventas_data = {
    'ID Venta': range(1, 101),
    'Fecha': [],
    'ID Cliente': [],
    'ID Producto': [],
    'Cantidad': [],
    'Total': []
}

for _ in range(100):
    fecha = faker.date_between(start_date='-1y', end_date='today').strftime('%Y/%m/%d')
    id_cliente = random.choice(clientes_df['ID'])
    id_producto = random.choice(productos_df['ID Producto'])
    cantidad = random.randint(1, 10)
    precio_producto = productos_df.loc[productos_df['ID Producto'] == id_producto, 'Precio USD'].values[0]
    total = cantidad * precio_producto

    ventas_data['Fecha'].append(fecha)
    ventas_data['ID Cliente'].append(id_cliente)
    ventas_data['ID Producto'].append(id_producto)
    ventas_data['Cantidad'].append(cantidad)
    ventas_data['Total'].append(total)

ventas_df = pd.DataFrame(ventas_data)
display(ventas_df)

    ID Venta       Fecha  ID Cliente  ID Producto  Cantidad  Total
0          1  2023/02/25  7937817390           80         2  10826
1          2  2022/12/15  7084039501           49         4  14340
2          3  2023/06/15  7316318910            9        10   6520
3          4  2022/08/05  6002562639           30         9  14481
4          5  2022/12/16  8452309104           89        10  11500
..       ...         ...         ...          ...       ...    ...
95        96  2023/04/22  1530122807           97         3   2238
96        97  2023/07/06  7608539109           82         2   5312
97        98  2023/02/20  7047127168           20        10  50670
98        99  2023/03/02  7316318910           83         4   4172
99       100  2022/09/17  1152685954            9         4   2608

[100 rows x 6 columns]

In [21]:
# Crear tabla de Opciones
opiniones_data = {
    'ID opinión': range(1, 101),
    'ID Cliente': [],
    'ID Producto': [],
    'Opinión': []
}

for _, row in ventas_df.iterrows():
    id_cliente = row['ID Cliente']
    id_producto = row['ID Producto']
    cantidad = row['Cantidad']

    if cantidad > 1:
        max_precio = productos_df.loc[productos_df['ID Producto'] == id_producto, 'Precio USD'].values[0]
        for _, venta in ventas_df.loc[ventas_df['ID Cliente'] == id_cliente].iterrows():
            venta_id_producto = venta['ID Producto']
            venta_precio = productos_df.loc[productos_df['ID Producto'] == venta_id_producto, 'Precio USD'].values[0]
            if venta_precio > max_precio:
                max_precio = venta_precio
                id_producto = venta_id_producto

    opinion = random.choice(['None', 'Mala', 'Regular', 'Aceptable', 'Buena', 'Excelente'])
    opiniones_data['ID Cliente'].append(id_cliente)
    opiniones_data['ID Producto'].append(id_producto)
    opiniones_data['Opinión'].append(opinion)

opiniones_df = pd.DataFrame(opiniones_data)

display(opiniones_df)

    ID opinión  ID Cliente  ID Producto    Opinión
0            1  7937817390           80    Regular
1            2  7084039501           58  Aceptable
2            3  7316318910           45    Regular
3            4  6002562639           30       Mala
4            5  8452309104           85      Buena
..         ...         ...          ...        ...
95          96  1530122807           97       None
96          97  7608539109           58       Mala
97          98  7047127168           20       Mala
98          99  7316318910           45      Buena
99         100  1152685954           23    Regular

[100 rows x 4 columns]

In [ ]:
from google.colab import files

# Exportar a Excel
clientes_df.to_excel('clientes.xlsx', index=False)
productos_df.to_excel('productos.xlsx', index=False)
ventas_df.to_excel('ventas.xlsx', index=False)
opiniones_df.to_excel('opiniones.xlsx', index=False)

# Descargar los archivos de Excel
files.download('clientes.xlsx')
files.download('productos.xlsx')
files.download('ventas.xlsx')
files.download('opiniones.xlsx')